# Generated by Django 5.0 on 2024-01-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='blank item')),
                ('description', models.TextField(default='blank description')),
                ('price', models.FloatField()),
            ],
        ),
    ]
